name: Fly Deploy
on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: cd frontend && rm -rf build && npm i && npm run build
        - run: flyctl deploy
